name: Git Hub Actions-Test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v2              
              with: 
                node-version: '16'

            - name: Install dependences
              run: npm ci