name: Git Hub Actions-Test

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v2              
              with: 
                node-version: '20'

            - name: Install dependences
              run: npm install

            - name: Run test
              run: npm test

            - name: Run build
              run: npm run build

            - name: Install GitHub CLI
              run: |
                curl -sSL https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_linux_amd64.tar.gz -o ghcli.tar.gz
                tar xvf ghcli.tar.gz
                sudo mv gh_2.0.0_linux_amd64/bin/gh /usr/local/bin/
                rm -rf gh_2.0.0_linux_amd64 ghcli.tar.gz
                
            - name: Create release
              run: |
                curl -X POST \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Authorization: token ${{ secrets.GH_PAT }}" \
                  https://api.github.com/repos/CosWorking/GitHubActions-Test/releases \
                  -d '{
                    "name": "Release",
                    "body": "Release notes",
                    "draft": false,
                    "prerelease": false
                  }'
              env:
                GH_TOKEN: ${{ secrets.GH_PAT }}
              

            - name: Send failure notification
              if: failure()
              uses: dawidd6/action-send-mail@v2
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{secrets.MAIL_USERNAME}}
                password: ${{secrets.MAIL_PASSWORD}}
                subject: CI/CD Pipeline failed
                to: gabriel.cosmai@outlook.com
                from: cosmaigabriel26@gmail.com
                body: The CI/CD pipeline failed. Please check the GitHub Actions log for more details.

    deploy:
      needs: build
      runs-on: ubuntu-latest
      environment: 
        name: production
        url: ${{ steps.deploy.outputs.url }}
      steps:
        - name: Deploy to production
          id: deploy
          run: npm run start
              