name: Git Hub Actions-Test

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v2              
              with: 
                node-version: '16'

            - name: Install dependences
              run: npm install

            - name: Run test
              run: npm test

            - name: Run build
              run: npm run build

            - name: Install GitHub CLI
              run: |
                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
                sudo apt-add-repository https://cli.github.com/packages
                sudo apt update
                sudo apt install gh

            - name: Create release
              run: |
                gh release create ${{ github.ref }} ./dist/my-app.zip -t "Release ${{ github.ref }}" -n "Release notes"
              env: 
                GH_TOKEN: ${{ secrets.TOKEN }}

            - name: Send failure notification
              if: failure()
              uses: dawidd6/action-send-mail@v2
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{secrets.MAIL_USERNAME}}
                password: ${{secrets.MAIL_PASSWORD}}
                subject: CI/CD Pipeline failed
                to: gabriel.cosmai@outlook.com
                from: cosmaigabriel26@gmail.com
                body: The CI/CD pipeline failed. Please check the GitHub Actions log for more details.